steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
          [
              "build",
              "-t",
              "australia-southeast1-docker.pkg.dev/sit737-23t1-williams-5d0e7b3/sit737-docker-repo/cal_ms:v1.0.0",
              ".",
          ]
images:
    - "australia-southeast1-docker.pkg.dev/sit737-23t1-williams-5d0e7b3/sit737-docker-repo/cal_ms:v1.0.0"
